### ISSUE TITLE
Can bagit profile be used to implement other dataset descriptions?

### ISSUE THREAD

**Issue by jmcmurry** [bagit-profiles/bagit-profiles-specification#12]
Forgive my shallow understanding but could the bagit profiles be used to exchange bags compliant with the HCLS dataset description?

**Comment by mjordan** [comment]
@jmcmurry  While there's nothing preventing you from packaging up a dataset in a Bag that complies with HCLS (BagIt profiles are agnostic to the content in the bag's `/data` directory), I am having a hard time imagining how the constraints imposed by Bagit profiles can be used, at least directly, to express aspects of HCLS descriptions or workflows. Perhaps others might be able to provide a more informed answer.

**Comment by jscancella** [comment]
@ruebot I think we should close this, do you agree?
